name = "WeatherApp"        # name of your worker
main = "index.js"             # entry point file
compatibility_date = "2025-08-13"

account_id = "axvampire" # find in Cloudflare dashboard → Overview
workers_dev = true             # enables temporary *.workers.dev domain